import { Level, Question } from './types';

export const BEGINNER_QUESTIONS: Question[] = [
  { id: 'b41', text: "I ___ a book every week.", options: ["read", "reads", "reading", "to read"], correctAnswer: "read", topic: "Verb Conjugation" },
  { id: 'b42', text: "She ___ not like pizza.", options: ["do", "does", "is", "has"], correctAnswer: "does", topic: "Negatives" },
  { id: 'b43', text: "___ they your friends?", options: ["Am", "Is", "Are", "Be"], correctAnswer: "Are", topic: "Verb Conjugation (To Be)" },
  { id: 'b44', text: "We ___ to the park yesterday.", options: ["go", "goes", "went", "going"], correctAnswer: "went", topic: "Past Simple" },
  { id: 'b45', text: "My brother ___ a new job.", options: ["have", "has", "is", "do"], correctAnswer: "has", topic: "Subject-Verb Agreement" },
  { id: 'b46', text: "___ you have a pen?", options: ["Do", "Does", "Are", "Is"], correctAnswer: "Do", topic: "Questions" },
  { id: 'b47', text: "Listen! The baby ___.", options: ["cry", "cries", "is crying", "crying"], correctAnswer: "is crying", topic: "Present Continuous" },
  { id: 'b48', text: "I ___ born in 1995.", options: ["am", "was", "were", "be"], correctAnswer: "was", topic: "Past Simple" },
  { id: 'b49', text: "They ___ not at home.", options: ["am", "is", "are", "be"], correctAnswer: "are", topic: "Verb Conjugation (To Be)" },
  { id: 'b50', text: "She ___ her teeth twice a day.", options: ["brush", "brushes", "brushing", "brushed"], correctAnswer: "brushes", topic: "Verb Conjugation" },
  { id: 'b51', text: "___ is the weather like?", options: ["How", "What", "Where", "Who"], correctAnswer: "What", topic: "Question Words" },
  { id: 'b52', text: "We ___ a great time last night.", options: ["have", "has", "had", "having"], correctAnswer: "had", topic: "Past Simple" },
  { id: 'b53', text: "I ___ going to the store.", options: ["am", "is", "are", "be"], correctAnswer: "am", topic: "Present Continuous" },
  { id: 'b54', text: "___ he your teacher?", options: ["Do", "Does", "Is", "Are"], correctAnswer: "Is", topic: "Verb Conjugation (To Be)" },
  { id: 'b55', text: "They ___ to the radio every morning.", options: ["listen", "listens", "listening", "listened"], correctAnswer: "listen", topic: "Present Simple" },
  { id: 'b56', text: "My sister ___ very tall.", options: ["am", "is", "are", "be"], correctAnswer: "is", topic: "Verb Conjugation (To Be)" },
  { id: 'b57', text: "I ___ not have any money.", options: ["do", "does", "am", "is"], correctAnswer: "do", topic: "Negatives" },
  { id: 'b58', text: "___ you like to dance?", options: ["Do", "Does", "Are", "Is"], correctAnswer: "Do", topic: "Questions" },
  { id: 'b59', text: "She ___ a beautiful song.", options: ["sing", "sings", "singing", "sang"], correctAnswer: "sings", topic: "Subject-Verb Agreement" },
  { id: 'b60', text: "We ___ in London.", options: ["live", "lives", "living", "lived"], correctAnswer: "live", topic: "Present Simple" },
  { id: 'b61', text: "I ___ a student at this university.", options: ["am", "is", "are", "be"], correctAnswer: "am", topic: "Verb Conjugation (To Be)" },
  { id: 'b62', text: "He ___ not want to go.", options: ["do", "does", "is", "has"], correctAnswer: "does", topic: "Negatives" },
  { id: 'b63', text: "___ they coming with us?", options: ["Do", "Does", "Are", "Is"], correctAnswer: "Are", topic: "Present Continuous" },
  { id: 'b64', text: "We ___ a big breakfast this morning.", options: ["eat", "eats", "ate", "eating"], correctAnswer: "ate", topic: "Past Simple" },
  { id: 'b65', text: "My mother ___ delicious cakes.", options: ["make", "makes", "making", "made"], correctAnswer: "makes", topic: "Subject-Verb Agreement" },
  { id: 'b66', text: "___ you see that bird?", options: ["Do", "Does", "Are", "Is"], correctAnswer: "Do", topic: "Questions" },
  { id: 'b67', text: "It ___ very cold today.", options: ["am", "is", "are", "be"], correctAnswer: "is", topic: "Verb Conjugation (To Be)" },
  { id: 'b68', text: "I ___ not know the answer.", options: ["do", "does", "am", "is"], correctAnswer: "do", topic: "Negatives" },
  { id: 'b69', text: "___ she have a brother?", options: ["Do", "Does", "Is", "Are"], correctAnswer: "Does", topic: "Questions" },
  { id: 'b70', text: "They ___ very happy together.", options: ["am", "is", "are", "be"], correctAnswer: "are", topic: "Verb Conjugation (To Be)" }
];

export const INTERMEDIATE_QUESTIONS: Question[] = [
  { id: 'i11', text: "I ___ my keys. Have you seen them?", options: ["lost", "have lost", "had lost", "lose"], correctAnswer: "have lost", topic: "Present Perfect" },
  { id: 'i12', text: "She ___ here since 2010.", options: ["works", "is working", "has been working", "worked"], correctAnswer: "has been working", topic: "Present Perfect Continuous" },
  { id: 'i13', text: "If it ___ tomorrow, we will stay at home.", options: ["rains", "will rain", "rain", "rained"], correctAnswer: "rains", topic: "First Conditional" },
  { id: 'i14', text: "I ___ to the cinema for ages.", options: ["didn't go", "haven't gone", "don't go", "wasn't going"], correctAnswer: "haven't gone", topic: "Present Perfect" },
  { id: 'i15', text: "The book ___ by a famous author.", options: ["wrote", "was written", "is writing", "has written"], correctAnswer: "was written", topic: "Passive Voice" },
  { id: 'i16', text: "I ___ my homework when the phone rang.", options: ["did", "was doing", "have done", "do"], correctAnswer: "was doing", topic: "Past Continuous" },
  { id: 'i17', text: "You ___ better see a doctor.", options: ["should", "had", "would", "must"], correctAnswer: "had", topic: "Advice (Had better)" },
  { id: 'i18', text: "I wish I ___ more money.", options: ["have", "had", "would have", "will have"], correctAnswer: "had", topic: "Wishes" },
  { id: 'i19', text: "He ___ be at home. I saw his car outside.", options: ["must", "can't", "might", "should"], correctAnswer: "must", topic: "Modals of Deduction" },
  { id: 'i20', text: "They ___ married for twenty years.", options: ["are", "have been", "were", "had been"], correctAnswer: "have been", topic: "Present Perfect" },
  { id: 'i21', text: "I'm used to ___ up early.", options: ["get", "getting", "to get", "got"], correctAnswer: "getting", topic: "Used to / Be used to" },
  { id: 'i22', text: "She asked me where ___.", options: ["did I live", "I lived", "do I live", "I live"], correctAnswer: "I lived", topic: "Reported Questions" },
  { id: 'i23', text: "I ___ go to the party, but I'm not sure.", options: ["must", "might", "should", "will"], correctAnswer: "might", topic: "Modals of Possibility" },
  { id: 'i24', text: "The car ___ repaired at the moment.", options: ["is", "is being", "has been", "was"], correctAnswer: "is being", topic: "Passive Voice (Continuous)" },
  { id: 'i25', text: "I ___ my hair cut yesterday.", options: ["had", "got", "made", "did"], correctAnswer: "had", topic: "Causative" },
  { id: 'i26', text: "By the time we arrived, the film ___.", options: ["started", "has started", "had started", "was starting"], correctAnswer: "had started", topic: "Past Perfect" },
  { id: 'i27', text: "I ___ rather stay at home tonight.", options: ["should", "would", "had", "will"], correctAnswer: "would", topic: "Preferences (Would rather)" },
  { id: 'i28', text: "He is the man ___ car was stolen.", options: ["who", "whom", "whose", "which"], correctAnswer: "whose", topic: "Relative Clauses" },
  { id: 'i29', text: "I'm looking forward to ___ you.", options: ["see", "seeing", "to see", "seen"], correctAnswer: "seeing", topic: "Preposition + Gerund" },
  { id: 'i30', text: "You ___ have told me! I was so worried.", options: ["should", "must", "might", "could"], correctAnswer: "should", topic: "Past Modals" },
  { id: 'i31', text: "I ___ to go now, I'm late.", options: ["must", "have", "should", "need"], correctAnswer: "have", topic: "Obligation" },
  { id: 'i32', text: "She ___ be very tired after such a long journey.", options: ["must", "can", "should", "will"], correctAnswer: "must", topic: "Modals of Deduction" },
  { id: 'i33', text: "I ___ my homework yet.", options: ["didn't finish", "haven't finished", "don't finish", "wasn't finishing"], correctAnswer: "haven't finished", topic: "Present Perfect" },
  { id: 'i34', text: "If I ___ more time, I would travel more.", options: ["have", "had", "will have", "would have"], correctAnswer: "had", topic: "Second Conditional" },
  { id: 'i35', text: "The house ___ built in 1920.", options: ["is", "was", "has been", "had been"], correctAnswer: "was", topic: "Passive Voice" },
  { id: 'i36', text: "I ___ a book when you called.", options: ["read", "was reading", "have read", "am reading"], correctAnswer: "was reading", topic: "Past Continuous" },
  { id: 'i37', text: "You ___ not park here.", options: ["must", "should", "can", "will"], correctAnswer: "must", topic: "Modals of Prohibition" },
  { id: 'i38', text: "I ___ been waiting for an hour.", options: ["am", "have", "was", "had"], correctAnswer: "have", topic: "Present Perfect Continuous" },
  { id: 'i39', text: "He said he ___ coming.", options: ["is", "was", "will be", "has been"], correctAnswer: "was", topic: "Reported Speech" },
  { id: 'i40', text: "I ___ like to have a coffee.", options: ["should", "would", "will", "could"], correctAnswer: "would", topic: "Polite Requests" },
  { id: 'i41', text: "I ___ my dinner when you arrived.", options: ["just finished", "had just finished", "have just finished", "was just finishing"], correctAnswer: "had just finished", topic: "Past Perfect" },
  { id: 'i42', text: "She ___ to be a doctor since she was a child.", options: ["wants", "is wanting", "has wanted", "wanted"], correctAnswer: "has wanted", topic: "Present Perfect" },
  { id: 'i43', text: "If I ___ the lottery, I would buy a boat.", options: ["win", "won", "will win", "had won"], correctAnswer: "won", topic: "Second Conditional" },
  { id: 'i44', text: "I ___ to the gym three times a week.", options: ["go", "am going", "have gone", "went"], correctAnswer: "go", topic: "Present Simple" },
  { id: 'i45', text: "The bridge ___ by next year.", options: ["will build", "will be built", "is building", "has been built"], correctAnswer: "will be built", topic: "Passive Voice (Future)" },
  { id: 'i46', text: "I ___ for my exam all night.", options: ["studied", "was studying", "have studied", "had been studying"], correctAnswer: "was studying", topic: "Past Continuous" },
  { id: 'i47', text: "You ___ to bring your passport.", options: ["must", "should", "need", "ought"], correctAnswer: "need", topic: "Modals" },
  { id: 'i48', text: "I wish I ___ swim.", options: ["can", "could", "would", "will"], correctAnswer: "could", topic: "Wishes" },
  { id: 'i49', text: "He ___ have forgotten about the meeting.", options: ["must", "can", "should", "will"], correctAnswer: "must", topic: "Modals of Deduction" },
  { id: 'i50', text: "They ___ living here for five years.", options: ["are", "have been", "were", "had been"], correctAnswer: "have been", topic: "Present Perfect Continuous" },
  { id: 'i51', text: "I'm looking forward to ___ you again.", options: ["meet", "meeting", "to meet", "met"], correctAnswer: "meeting", topic: "Preposition + Gerund" },
  { id: 'i52', text: "She asked me if I ___ help her.", options: ["can", "could", "will", "would"], correctAnswer: "could", topic: "Reported Speech" },
  { id: 'i53', text: "I ___ go to the party if I'm not too tired.", options: ["must", "might", "should", "will"], correctAnswer: "might", topic: "Modals of Possibility" },
  { id: 'i54', text: "The room ___ cleaned every day.", options: ["is", "is being", "has been", "was"], correctAnswer: "is", topic: "Passive Voice" },
  { id: 'i55', text: "I ___ my car washed yesterday.", options: ["had", "got", "made", "did"], correctAnswer: "had", topic: "Causative" },
  { id: 'i56', text: "By the time he arrived, we ___ dinner.", options: ["finished", "has finished", "had finished", "was finishing"], correctAnswer: "had finished", topic: "Past Perfect" },
  { id: 'i57', text: "I ___ rather you didn't smoke in here.", options: ["should", "would", "had", "will"], correctAnswer: "would", topic: "Preferences" },
  { id: 'i58', text: "He is the man ___ lives next door.", options: ["who", "whom", "whose", "which"], correctAnswer: "who", topic: "Relative Clauses" },
  { id: 'i59', text: "I'm thinking of ___ a new car.", options: ["buy", "buying", "to buy", "bought"], correctAnswer: "buying", topic: "Preposition + Gerund" },
  { id: 'i60', text: "You ___ have told me the truth.", options: ["should", "must", "might", "could"], correctAnswer: "should", topic: "Past Modals" },
  { id: 'i61', text: "I ___ to go now, I'm late.", options: ["must", "have", "should", "need"], correctAnswer: "have", topic: "Obligation" },
  { id: 'i62', text: "She ___ be very happy with her new job.", options: ["must", "can", "should", "will"], correctAnswer: "must", topic: "Modals of Deduction" },
  { id: 'i63', text: "I ___ my homework yet.", options: ["didn't finish", "haven't finished", "don't finish", "wasn't finishing"], correctAnswer: "haven't finished", topic: "Present Perfect" },
  { id: 'i64', text: "If I ___ more money, I would buy a house.", options: ["have", "had", "will have", "would have"], correctAnswer: "had", topic: "Second Conditional" },
  { id: 'i65', text: "The house ___ built in 1920.", options: ["is", "was", "has been", "had been"], correctAnswer: "was", topic: "Passive Voice" },
  { id: 'i66', text: "I ___ a book when you called.", options: ["read", "was reading", "have read", "am reading"], correctAnswer: "was reading", topic: "Past Continuous" },
  { id: 'i67', text: "You ___ not park here.", options: ["must", "should", "can", "will"], correctAnswer: "must", topic: "Modals of Prohibition" },
  { id: 'i68', text: "I ___ been waiting for an hour.", options: ["am", "have", "was", "had"], correctAnswer: "have", topic: "Present Perfect Continuous" },
  { id: 'i69', text: "He said he ___ coming.", options: ["is", "was", "will be", "has been"], correctAnswer: "was", topic: "Reported Speech" },
  { id: 'i70', text: "I ___ like to have a coffee.", options: ["should", "would", "will", "could"], correctAnswer: "would", topic: "Polite Requests" }
];

export const ADVANCED_QUESTIONS: Question[] = [
  { id: 'a11', text: "Never ___ such a beautiful sunset.", options: ["I have seen", "have I seen", "I saw", "did I see"], correctAnswer: "have I seen", topic: "Inversion" },
  { id: 'a12', text: "It is essential that he ___ here on time.", options: ["is", "be", "was", "will be"], correctAnswer: "be", topic: "Subjunctive" },
  { id: 'a13', text: "___ for the rain, we would have had a picnic.", options: ["But", "Had it not been", "If it wasn't", "Were it not"], correctAnswer: "Had it not been", topic: "Third Conditional (Inversion)" },
  { id: 'a14', text: "I'd rather you ___ tell anyone about this.", options: ["don't", "didn't", "not", "won't"], correctAnswer: "didn't", topic: "Unreal Past" },
  { id: 'a15', text: "No sooner ___ the house than it started to pour.", options: ["I had left", "had I left", "I left", "did I leave"], correctAnswer: "had I left", topic: "Inversion" },
  { id: 'a16', text: "I suggested that she ___ a lawyer.", options: ["sees", "see", "saw", "should see"], correctAnswer: "see", topic: "Subjunctive" },
  { id: 'a17', text: "Try ___ he might, he couldn't open the door.", options: ["as", "though", "however", "although"], correctAnswer: "as", topic: "Concession Clauses" },
  { id: 'a18', text: "He was seen ___ the building late at night.", options: ["leave", "leaving", "to leave", "left"], correctAnswer: "leaving", topic: "Verbs of Perception" },
  { id: 'a19', text: "Should you ___ any help, please let me know.", options: ["need", "needed", "will need", "should need"], correctAnswer: "need", topic: "Conditional Inversion" },
  { id: 'a20', text: "I'd sooner ___ than go to that party.", options: ["die", "to die", "dying", "died"], correctAnswer: "die", topic: "Preferences" },
  { id: 'a21', text: "Little ___ I know that he was lying.", options: ["I did", "did I", "I had", "had I"], correctAnswer: "did I", topic: "Inversion" },
  { id: 'a22', text: "It's about time we ___.", options: ["leave", "left", "leaving", "to leave"], correctAnswer: "left", topic: "Unreal Past" },
  { id: 'a23', text: "So ___ was the weather that we stayed indoors.", options: ["bad", "badly", "such bad", "a bad"], correctAnswer: "bad", topic: "Inversion with So/Such" },
  { id: 'a24', text: "I object to ___ treated like a child.", options: ["be", "being", "to be", "been"], correctAnswer: "being", topic: "Gerunds after Prepositions" },
  { id: 'a25', text: "Were I ___ in your shoes, I'd be careful.", options: ["be", "to be", "being", "been"], correctAnswer: "to be", topic: "Conditional Inversion" },
  { id: 'a26', text: "He was accused of ___ the money.", options: ["steal", "stealing", "to steal", "stolen"], correctAnswer: "stealing", topic: "Gerunds" },
  { id: 'a27', text: "Not only ___ he late, but he also forgot his keys.", options: ["is", "was", "did", "had"], correctAnswer: "was", topic: "Inversion" },
  { id: 'a28', text: "I'd rather you ___ smoke in here.", options: ["don't", "didn't", "not", "won't"], correctAnswer: "didn't", topic: "Preferences" },
  { id: 'a29', text: "Scarcely ___ I sat down when the phone rang.", options: ["I had", "had I", "I did", "did I"], correctAnswer: "had I", topic: "Inversion" },
  { id: 'a30', text: "It is high time he ___ a job.", options: ["finds", "found", "finding", "to find"], correctAnswer: "found", topic: "Unreal Past" },
  { id: 'a31', text: "Only then ___ I realize my mistake.", options: ["I did", "did I", "I had", "had I"], correctAnswer: "did I", topic: "Inversion" },
  { id: 'a32', text: "I wish I ___ better at English.", options: ["am", "was", "were", "be"], correctAnswer: "were", topic: "Wishes" },
  { id: 'a33', text: "Under no circumstances ___ you leave the room.", options: ["you should", "should you", "you must", "must you"], correctAnswer: "should you", topic: "Inversion" },
  { id: 'a34', text: "I'd rather ___ gone to the party.", options: ["not have", "haven't", "not", "didn't"], correctAnswer: "not have", topic: "Past Preferences" },
  { id: 'a35', text: "Hardly ___ I started when it began to rain.", options: ["I had", "had I", "I did", "did I"], correctAnswer: "had I", topic: "Inversion" },
  { id: 'a36', text: "It is important that he ___ the truth.", options: ["knows", "know", "knew", "should know"], correctAnswer: "know", topic: "Subjunctive" },
  { id: 'a37', text: "Were it not for your help, I ___ fail.", options: ["will", "would", "would have", "did"], correctAnswer: "would", topic: "Conditionals" },
  { id: 'a38', text: "Not until I saw him ___ I believe it.", options: ["I did", "did I", "I had", "had I"], correctAnswer: "did I", topic: "Inversion" },
  { id: 'a39', text: "I'd sooner you ___ here.", options: ["stay", "stayed", "staying", "to stay"], correctAnswer: "stayed", topic: "Preferences" },
  { id: 'a40', text: "Seldom ___ we see such talent.", options: ["we do", "do we", "we have", "have we"], correctAnswer: "do we", topic: "Inversion" },
  { id: 'a41', text: "Hardly ___ the door when the phone rang.", options: ["I had opened", "had I opened", "I opened", "did I open"], correctAnswer: "had I opened", topic: "Inversion" },
  { id: 'a42', text: "It is vital that she ___ the meeting.", options: ["attends", "attend", "attended", "should attend"], correctAnswer: "attend", topic: "Subjunctive" },
  { id: 'a43', text: "___ it not for his intervention, the deal would have failed.", options: ["But", "Had", "If", "Were"], correctAnswer: "Had", topic: "Conditional Inversion" },
  { id: 'a44', text: "I'd rather you ___ speak to him like that.", options: ["don't", "didn't", "not", "won't"], correctAnswer: "didn't", topic: "Unreal Past" },
  { id: 'a45', text: "No sooner ___ the news than she burst into tears.", options: ["she had heard", "had she heard", "she heard", "did she hear"], correctAnswer: "had she heard", topic: "Inversion" },
  { id: 'a46', text: "I suggested that he ___ a doctor.", options: ["sees", "see", "saw", "should see"], correctAnswer: "see", topic: "Subjunctive" },
  { id: 'a47', text: "Much ___ I'd like to help, I'm afraid I can't.", options: ["as", "though", "however", "although"], correctAnswer: "as", topic: "Concession Clauses" },
  { id: 'a48', text: "He was observed ___ the premises after hours.", options: ["enter", "entering", "to enter", "entered"], correctAnswer: "entering", topic: "Verbs of Perception" },
  { id: 'a49', text: "Should you ___ any further information, please contact us.", options: ["need", "needed", "will need", "should need"], correctAnswer: "need", topic: "Conditional Inversion" },
  { id: 'a50', text: "I'd sooner ___ hungry than eat that.", options: ["go", "to go", "going", "went"], correctAnswer: "go", topic: "Preferences" },
  { id: 'a51', text: "Little ___ we realize the danger we were in.", options: ["we did", "did we", "we had", "had we"], correctAnswer: "did we", topic: "Inversion" },
  { id: 'a52', text: "It's high time you ___ a decision.", options: ["make", "made", "making", "to make"], correctAnswer: "made", topic: "Unreal Past" },
  { id: 'a53', text: "So ___ was the noise that I couldn't sleep.", options: ["loud", "loudly", "such loud", "a loud"], correctAnswer: "loud", topic: "Inversion" },
  { id: 'a54', text: "I object to ___ treated as if I were a child.", options: ["be", "being", "to be", "been"], correctAnswer: "being", topic: "Gerunds after Prepositions" },
  { id: 'a55', text: "Were I ___ in your position, I'd be worried.", options: ["be", "to be", "being", "been"], correctAnswer: "to be", topic: "Conditional Inversion" },
  { id: 'a56', text: "He was accused of ___ the company's funds.", options: ["misuse", "misusing", "to misuse", "misused"], correctAnswer: "misusing", topic: "Gerunds" },
  { id: 'a57', text: "Not only ___ he fail the exam, but he also lost his job.", options: ["is", "was", "did", "had"], correctAnswer: "did", topic: "Inversion" },
  { id: 'a58', text: "I'd rather you ___ mention this to anyone.", options: ["don't", "didn't", "not", "won't"], correctAnswer: "didn't", topic: "Preferences" },
  { id: 'a59', text: "Scarcely ___ I arrived when the meeting started.", options: ["I had", "had I", "I did", "did I"], correctAnswer: "had I", topic: "Inversion" },
  { id: 'a60', text: "It is about time he ___ a job.", options: ["finds", "found", "finding", "to find"], correctAnswer: "found", topic: "Unreal Past" },
  { id: 'a61', text: "Only then ___ I understand the gravity of the situation.", options: ["I did", "did I", "I had", "had I"], correctAnswer: "did I", topic: "Inversion" },
  { id: 'a62', text: "I wish I ___ more time to finish the project.", options: ["have", "had", "will have", "would have"], correctAnswer: "had", topic: "Wishes" },
  { id: 'a63', text: "Under no circumstances ___ you open that door.", options: ["you should", "should you", "you must", "must you"], correctAnswer: "should you", topic: "Inversion" },
  { id: 'a64', text: "I'd rather ___ gone to the cinema.", options: ["not have", "haven't", "not", "didn't"], correctAnswer: "not have", topic: "Past Preferences" },
  { id: 'a65', text: "Hardly ___ I started when the power went out.", options: ["I had", "had I", "I did", "did I"], correctAnswer: "had I", topic: "Inversion" },
  { id: 'a66', text: "It is imperative that he ___ the truth.", options: ["knows", "know", "knew", "should know"], correctAnswer: "know", topic: "Subjunctive" },
  { id: 'a67', text: "Were it not for your support, I ___ succeed.", options: ["will", "would", "would have", "did"], correctAnswer: "would", topic: "Conditionals" },
  { id: 'a68', text: "Not until I saw the evidence ___ I believe him.", options: ["I did", "did I", "I had", "had I"], correctAnswer: "did I", topic: "Inversion" },
  { id: 'a69', text: "I'd sooner you ___ at home.", options: ["stay", "stayed", "staying", "to stay"], correctAnswer: "stayed", topic: "Preferences" },
  { id: 'a70', text: "Seldom ___ we encounter such brilliance.", options: ["we do", "do we", "we have", "have we"], correctAnswer: "do we", topic: "Inversion" }
];

export const EXPERT_QUESTIONS: Question[] = [
  { id: 'e1', text: "___ he to have known the truth, he would have acted differently.", options: ["Had", "Were", "Should", "If"], correctAnswer: "Were", topic: "Advanced Conditionals" },
  { id: 'e2', text: "The committee insisted that the proposal ___ reconsidered.", options: ["is", "be", "was", "will be"], correctAnswer: "be", topic: "Subjunctive Mood" },
  { id: 'e3', text: "Not for one moment ___ that he was capable of such a thing.", options: ["I thought", "did I think", "I had thought", "had I thought"], correctAnswer: "did I think", topic: "Negative Inversion" },
  { id: 'e4', text: "Such ___ the intensity of the storm that the trees were uprooted.", options: ["is", "was", "be", "were"], correctAnswer: "was", topic: "Inversion with Such" },
  { id: 'e5', text: "I would rather you ___ mentioned this to the manager.", options: ["not", "didn't", "haven't", "hadn't"], correctAnswer: "hadn't", topic: "Past Unreal Preferences" },
  { id: 'e6', text: "___ the circumstances, we have no choice but to cancel.", options: ["Given", "Giving", "To give", "Having given"], correctAnswer: "Given", topic: "Participle Phrases" },
  { id: 'e7', text: "He is believed ___ the country under a false identity.", options: ["to leave", "to have left", "leaving", "having left"], correctAnswer: "to have left", topic: "Perfect Infinitive" },
  { id: 'e8', text: "Try ___ we might, we couldn't convince him to stay.", options: ["as", "though", "however", "although"], correctAnswer: "as", topic: "Concession with Try" },
  { id: 'e9', text: "It is high time the government ___ action on climate change.", options: ["takes", "took", "taking", "to take"], correctAnswer: "took", topic: "Unreal Past" },
  { id: 'e10', text: "Scarcely ___ the match started when it began to rain.", options: ["the match had", "had the match", "did the match", "the match did"], correctAnswer: "had the match", topic: "Inversion with Scarcely" }
];
